name: Testing Token

on:
  workflow_dispatch:

jobs:
  testtoken:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Token Repository
        uses: actions/checkout@v4
        with:
          repository: sjbabu/token
          ref: main
          token: ${{ secrets.all_access }}
          path: token

      - name: Checkout CICD Repository
        uses: actions/checkout@v4
        with:
          repository: sjbabu/cicd
          ref: main
          token: ${{ secrets.all_access }}
          path: cicd

      - name: Verify
        run: |
          pwd
          ls -la
          ls -la token
          ls -la cicd
