name: Testing token
on: workflow_dispatch
jobs:
  testtoken:
    runs-on: ubuntu-latest
    steps:
    - name: print token
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}"
    - name: Checkout Other Repository
      uses: actions/checkout@v7
      with:
          repository: sjbabu/token
          ref: main
          token: ${{ secrets.TEST_TOKEN }}
    - name: Checkout Other Repository testtoken
      uses: actions/checkout@v7
      with:
          repository: sjbabu/cicd
          ref: main
          token: ${{ secrets.TEST_TOKEN }}
    - name: os coammnds
      run: |
        ls -a
        pwd
