name: Testing token
on: workflow_dispatch
jobs:
  testtoken:
    runs-on: ubuntu-latest
    steps:
    - name: print token
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}"
    - name: clone other repo
      uses: actions/checkout@v7
      with:
        repository: sjbabu/cicd
